@host = http://localhost:3000
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjF9.RfopwvQBbCp4QP3VGyYMR6CcjBKBlbhf2aIFIZFCLmU

############### ADMIN USER ###############

### Get all users
GET {{host}}/api/admin/user/?limit=4
Authorization: {{tokenAdmin}}

### Get a user info
GET {{host}}/api/admin/user/21
Authorization: {{tokenAdmin}}

### Update a user info
PUT {{host}}/api/admin/user/21
Authorization: {{tokenAdmin}}
Content-Type: application/json

{
    "email": "andry.html@gmail.com",
    "name": "Ssadry",
    "surname": "Reyes",
    "phone": "1234567890",
    "password": "12345"
}

### Delete a user
DELETE {{host}}/api/admin/user/22
Authorization: {{tokenAdmin}}



############### ADMIN REVIEWS ###############

### Get all reviews
GET {{host}}/api/admin/review?order=asc&page=1&limit=10
Authorization: {{tokenAdmin}}

### Get a review by ID
GET {{host}}/api/admin/review/9
Authorization: {{tokenAdmin}}

### Update a review
PUT {{host}}/api/admin/review/3
Authorization: {{tokenAdmin}}
Content-Type: application/json

{
    "rating": 1,
    "comment": "Great service!"
}

### Delete a review
DELETE {{host}}/api/admin/review/9
Authorization: {{tokenAdmin}}
