@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjF9.RfopwvQBbCp4QP3VGyYMR6CcjBKBlbhf2aIFIZFCLmU

### Reviews endpoints

### Create a review
POST {{host}}/api/review
Authorization: {{token}}
Content-Type: application/json

{
    "rating": 5,
    "comment": "ME CAGO EN LA PUTA8"
}

### Get all user reviews
GET {{host}}/api/review
Authorization: {{token}}

### Delete a review
DELETE {{host}}/api/review/2
Authorization: {{token}}


### Get all reviews
GET {{host}}/api/review/all



### Test endpoint
GET {{host}}/api/test
